/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminJobsIndexRouteImport } from './routes/_authenticated/admin.jobs.index'
import { Route as ApiPublicApplicationsIntakeRouteImport } from './routes/api/public/applications/intake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminJobsIndexRoute =
  AuthenticatedAdminJobsIndexRouteImport.update({
    id: '/admin/jobs/',
    path: '/admin/jobs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicApplicationsIntakeRoute =
  ApiPublicApplicationsIntakeRouteImport.update({
    id: '/api/public/applications/intake',
    path: '/api/public/applications/intake',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/applications/intake': typeof ApiPublicApplicationsIntakeRoute
  '/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers': typeof CareersIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/applications/intake': typeof ApiPublicApplicationsIntakeRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/applications/intake': typeof ApiPublicApplicationsIntakeRoute
  '/_authenticated/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/careers/$slug'
    | '/careers/'
    | '/admin/'
    | '/api/public/applications/intake'
    | '/admin/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/careers/$slug'
    | '/careers'
    | '/admin'
    | '/api/public/applications/intake'
    | '/admin/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/careers/$slug'
    | '/careers/'
    | '/_authenticated/admin/'
    | '/api/public/applications/intake'
    | '/_authenticated/admin/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  CareersSlugRoute: typeof CareersSlugRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ApiPublicApplicationsIntakeRoute: typeof ApiPublicApplicationsIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs/': {
      id: '/_authenticated/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedAdminJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/applications/intake': {
      id: '/api/public/applications/intake'
      path: '/api/public/applications/intake'
      fullPath: '/api/public/applications/intake'
      preLoaderRoute: typeof ApiPublicApplicationsIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminJobsIndexRoute: typeof AuthenticatedAdminJobsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminJobsIndexRoute: AuthenticatedAdminJobsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  CareersSlugRoute: CareersSlugRoute,
  CareersIndexRoute: CareersIndexRoute,
  ApiPublicApplicationsIntakeRoute: ApiPublicApplicationsIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
