/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as ExamTokenRouteImport } from './routes/exam.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminFormsRouteImport } from './routes/_authenticated/admin.forms'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminApplicationsIndexRouteImport } from './routes/_authenticated/admin.applications.index'
import { Route as AuthenticatedAdminApplicationsIdRouteImport } from './routes/_authenticated/admin.applications.$id'
import { Route as AuthenticatedAdminExamsIndexRouteImport } from './routes/_authenticated/admin.exams.index'
import { Route as AuthenticatedAdminExamsExamIdRouteImport } from './routes/_authenticated/admin.exams.$examId'
import { Route as AuthenticatedAdminExamsNewRouteImport } from './routes/_authenticated/admin.exams.new'
import { Route as AuthenticatedAdminJobsIndexRouteImport } from './routes/_authenticated/admin.jobs.index'
import { Route as AuthenticatedAdminJobsIdRouteImport } from './routes/_authenticated/admin.jobs.$id'
import { Route as AuthenticatedAdminJobsNewRouteImport } from './routes/_authenticated/admin.jobs.new'
import { Route as ApiPublicApplicationsIntakeRouteImport } from './routes/api/public/applications/intake'
import { Route as AuthenticatedAdminExamsAttemptsAttemptIdRouteImport } from './routes/_authenticated/admin.exams.attempts.$attemptId'
import { Route as AuthenticatedAdminExamsSubmissionsExamIdRouteImport } from './routes/_authenticated/admin.exams.submissions.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTokenRoute = ExamTokenRouteImport.update({
  id: '/exam/$token',
  path: '/exam/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFormsRoute = AuthenticatedAdminFormsRouteImport.update({
  id: '/admin/forms',
  path: '/admin/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/admin/profile',
    path: '/admin/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsIndexRoute =
  AuthenticatedAdminApplicationsIndexRouteImport.update({
    id: '/admin/applications/',
    path: '/admin/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsIdRoute =
  AuthenticatedAdminApplicationsIdRouteImport.update({
    id: '/admin/applications/$id',
    path: '/admin/applications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExamsIndexRoute =
  AuthenticatedAdminExamsIndexRouteImport.update({
    id: '/admin/exams/',
    path: '/admin/exams/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExamsExamIdRoute =
  AuthenticatedAdminExamsExamIdRouteImport.update({
    id: '/admin/exams/$examId',
    path: '/admin/exams/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExamsNewRoute =
  AuthenticatedAdminExamsNewRouteImport.update({
    id: '/admin/exams/new',
    path: '/admin/exams/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminJobsIndexRoute =
  AuthenticatedAdminJobsIndexRouteImport.update({
    id: '/admin/jobs/',
    path: '/admin/jobs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminJobsIdRoute =
  AuthenticatedAdminJobsIdRouteImport.update({
    id: '/admin/jobs/$id',
    path: '/admin/jobs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminJobsNewRoute =
  AuthenticatedAdminJobsNewRouteImport.update({
    id: '/admin/jobs/new',
    path: '/admin/jobs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicApplicationsIntakeRoute =
  ApiPublicApplicationsIntakeRouteImport.update({
    id: '/api/public/applications/intake',
    path: '/api/public/applications/intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminExamsAttemptsAttemptIdRoute =
  AuthenticatedAdminExamsAttemptsAttemptIdRouteImport.update({
    id: '/admin/exams/attempts/$attemptId',
    path: '/admin/exams/attempts/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExamsSubmissionsExamIdRoute =
  AuthenticatedAdminExamsSubmissionsExamIdRouteImport.update({
    id: '/admin/exams/submissions/$examId',
    path: '/admin/exams/submissions/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/exam/$token': typeof ExamTokenRoute
  '/careers/': typeof CareersIndexRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/api/public/applications/intake': typeof ApiPublicApplicationsIntakeRoute
  '/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
  '/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/exams/attempts/$attemptId': typeof AuthenticatedAdminExamsAttemptsAttemptIdRoute
  '/admin/exams/submissions/$examId': typeof AuthenticatedAdminExamsSubmissionsExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/exam/$token': typeof ExamTokenRoute
  '/careers': typeof CareersIndexRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/api/public/applications/intake': typeof ApiPublicApplicationsIntakeRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsIndexRoute
  '/admin/exams': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/exams/attempts/$attemptId': typeof AuthenticatedAdminExamsAttemptsAttemptIdRoute
  '/admin/exams/submissions/$examId': typeof AuthenticatedAdminExamsSubmissionsExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/exam/$token': typeof ExamTokenRoute
  '/careers/': typeof CareersIndexRoute
  '/_authenticated/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/_authenticated/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/_authenticated/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/_authenticated/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/_authenticated/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/api/public/applications/intake': typeof ApiPublicApplicationsIntakeRoute
  '/_authenticated/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
  '/_authenticated/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/_authenticated/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/_authenticated/admin/exams/attempts/$attemptId': typeof AuthenticatedAdminExamsAttemptsAttemptIdRoute
  '/_authenticated/admin/exams/submissions/$examId': typeof AuthenticatedAdminExamsSubmissionsExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/careers/$slug'
    | '/exam/$token'
    | '/careers/'
    | '/admin/forms'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/'
    | '/admin/applications/$id'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/jobs/$id'
    | '/admin/jobs/new'
    | '/api/public/applications/intake'
    | '/admin/applications/'
    | '/admin/exams/'
    | '/admin/jobs/'
    | '/admin/exams/attempts/$attemptId'
    | '/admin/exams/submissions/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/careers/$slug'
    | '/exam/$token'
    | '/careers'
    | '/admin/forms'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin'
    | '/admin/applications/$id'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/jobs/$id'
    | '/admin/jobs/new'
    | '/api/public/applications/intake'
    | '/admin/applications'
    | '/admin/exams'
    | '/admin/jobs'
    | '/admin/exams/attempts/$attemptId'
    | '/admin/exams/submissions/$examId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/careers/$slug'
    | '/exam/$token'
    | '/careers/'
    | '/_authenticated/admin/forms'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/applications/$id'
    | '/_authenticated/admin/exams/$examId'
    | '/_authenticated/admin/exams/new'
    | '/_authenticated/admin/jobs/$id'
    | '/_authenticated/admin/jobs/new'
    | '/api/public/applications/intake'
    | '/_authenticated/admin/applications/'
    | '/_authenticated/admin/exams/'
    | '/_authenticated/admin/jobs/'
    | '/_authenticated/admin/exams/attempts/$attemptId'
    | '/_authenticated/admin/exams/submissions/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  CareersSlugRoute: typeof CareersSlugRoute
  ExamTokenRoute: typeof ExamTokenRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ApiPublicApplicationsIntakeRoute: typeof ApiPublicApplicationsIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$token': {
      id: '/exam/$token'
      path: '/exam/$token'
      fullPath: '/exam/$token'
      preLoaderRoute: typeof ExamTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/forms': {
      id: '/_authenticated/admin/forms'
      path: '/admin/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AuthenticatedAdminFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications/': {
      id: '/_authenticated/admin/applications/'
      path: '/admin/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications/$id': {
      id: '/_authenticated/admin/applications/$id'
      path: '/admin/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/exams/': {
      id: '/_authenticated/admin/exams/'
      path: '/admin/exams'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AuthenticatedAdminExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/exams/$examId': {
      id: '/_authenticated/admin/exams/$examId'
      path: '/admin/exams/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AuthenticatedAdminExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/exams/new': {
      id: '/_authenticated/admin/exams/new'
      path: '/admin/exams/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AuthenticatedAdminExamsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs/': {
      id: '/_authenticated/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedAdminJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs/$id': {
      id: '/_authenticated/admin/jobs/$id'
      path: '/admin/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AuthenticatedAdminJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs/new': {
      id: '/_authenticated/admin/jobs/new'
      path: '/admin/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AuthenticatedAdminJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/applications/intake': {
      id: '/api/public/applications/intake'
      path: '/api/public/applications/intake'
      fullPath: '/api/public/applications/intake'
      preLoaderRoute: typeof ApiPublicApplicationsIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/exams/attempts/$attemptId': {
      id: '/_authenticated/admin/exams/attempts/$attemptId'
      path: '/admin/exams/attempts/$attemptId'
      fullPath: '/admin/exams/attempts/$attemptId'
      preLoaderRoute: typeof AuthenticatedAdminExamsAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/exams/submissions/$examId': {
      id: '/_authenticated/admin/exams/submissions/$examId'
      path: '/admin/exams/submissions/$examId'
      fullPath: '/admin/exams/submissions/$examId'
      preLoaderRoute: typeof AuthenticatedAdminExamsSubmissionsExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminFormsRoute: typeof AuthenticatedAdminFormsRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminApplicationsIdRoute: typeof AuthenticatedAdminApplicationsIdRoute
  AuthenticatedAdminExamsExamIdRoute: typeof AuthenticatedAdminExamsExamIdRoute
  AuthenticatedAdminExamsNewRoute: typeof AuthenticatedAdminExamsNewRoute
  AuthenticatedAdminJobsIdRoute: typeof AuthenticatedAdminJobsIdRoute
  AuthenticatedAdminJobsNewRoute: typeof AuthenticatedAdminJobsNewRoute
  AuthenticatedAdminApplicationsIndexRoute: typeof AuthenticatedAdminApplicationsIndexRoute
  AuthenticatedAdminExamsIndexRoute: typeof AuthenticatedAdminExamsIndexRoute
  AuthenticatedAdminJobsIndexRoute: typeof AuthenticatedAdminJobsIndexRoute
  AuthenticatedAdminExamsAttemptsAttemptIdRoute: typeof AuthenticatedAdminExamsAttemptsAttemptIdRoute
  AuthenticatedAdminExamsSubmissionsExamIdRoute: typeof AuthenticatedAdminExamsSubmissionsExamIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminFormsRoute: AuthenticatedAdminFormsRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminApplicationsIdRoute: AuthenticatedAdminApplicationsIdRoute,
  AuthenticatedAdminExamsExamIdRoute: AuthenticatedAdminExamsExamIdRoute,
  AuthenticatedAdminExamsNewRoute: AuthenticatedAdminExamsNewRoute,
  AuthenticatedAdminJobsIdRoute: AuthenticatedAdminJobsIdRoute,
  AuthenticatedAdminJobsNewRoute: AuthenticatedAdminJobsNewRoute,
  AuthenticatedAdminApplicationsIndexRoute:
    AuthenticatedAdminApplicationsIndexRoute,
  AuthenticatedAdminExamsIndexRoute: AuthenticatedAdminExamsIndexRoute,
  AuthenticatedAdminJobsIndexRoute: AuthenticatedAdminJobsIndexRoute,
  AuthenticatedAdminExamsAttemptsAttemptIdRoute:
    AuthenticatedAdminExamsAttemptsAttemptIdRoute,
  AuthenticatedAdminExamsSubmissionsExamIdRoute:
    AuthenticatedAdminExamsSubmissionsExamIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  CareersSlugRoute: CareersSlugRoute,
  ExamTokenRoute: ExamTokenRoute,
  CareersIndexRoute: CareersIndexRoute,
  ApiPublicApplicationsIntakeRoute: ApiPublicApplicationsIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
